version: "3.8"
services:
  database:
    image: 'mongo'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    #  context: ./backend
    #  dockerfile: Dockerfile
    #  args:
    ports:
      - '3000:3000'
    env_file:
      - ./env/backend.env
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend/src:/usr/src/app/src
    depends_on:
      - backend
volumes:
  data:
