version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    container_name: frontend-service
    networks:
      - fullstack-network
    volumes:
      - ./frontend/src:/usr/src/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    #  context: ./backend
    #  dockerfile: Dockerfile
    #  args:
    ports:
      - 3000:3000
    container_name: backend-service
    networks:
      - fullstack-network
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend/images:/usr/src/app/images
    depends_on:
      - database

  database:
    image: mongo
    restart: always
    container_name: mongodb-service
    ports:
      - 27017:27017
    networks:
      - fullstack-network
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env

networks:
  fullstack-network:
    driver: bridge

volumes:
  data:
